### ISSUE TITLE
which user?

### ISSUE THREAD

**Issue by eselahe** [cmlab/NetFPGA-1G-CML#4]
Hi,
which user is correct for installing NetFPGA-10G-live package and other required software such as ISE 14.6 ? also about projects? root or not?

**Comment by jhirata** [comment]
Hi eselahe,

That's a very good question. The wiki at 
https://github.com/NetFPGA/NetFPGA-public/wiki states that you should 
login as root and run everything as root. They suggest this because it's 
easier for them to support the project by having everyone log in as the 
root user. Root user has no restrictions to what they can do, therefore, 
you don't run into permissions problems very often. I believe that 
running everything as the root user is a security risk. If you aren't 
concerned about security, then running as the root user should be OK. 
However, I don't believe the code in this repository has been tested by 
running everything as root. I don't think there would be a problem doing 
everything as root, I just haven't tried it yet. If you decide to try 
doing everything as the root user, please let us know how it works out 
for you! It would be very helpful to us and the other users of this project.

I typically run as non root, but there are certain cases where you 
/must/ run as the root user. For example, I never run the Xilinx tools 
as the root user, but, I had to use `sudo` to install the Xilinx tools 
into my /opt/ folder. Another example: I don't build the reference nic 
driver as root, but I have to use `sudo` to load the driver. There are 
some cases where the hw tests might require you to be root as well. 
Usually, I try something as non root, and if it fails I'll try as root. 
This is more of a linux question in general as to when you should and 
shouldn't do things as the root user. I would suggest searching the web 
for why you should or shouldn't do things as the root user, there are 
certainly lots of people with strong opinions on the subject!

One thing that you need to look out for when you're running as a normal 
user: if you do something as the root user and the command produces 
files, you may not be able to use the files as a normal user because of 
permission problems. You can use root to change the file permissions of 
the files that you need, and it'll be ok, but it's just something to 
look out for.

I hope that this answers your questions. Feel free to search for more 
details on running things as the root user and file permissions for more 
details.

Thanks,
Jay

**Comment by eselahe** [comment]
Thank you very much for your detailed answer.

Best regards
elahe
